# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_appointment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=False),
            preserve_default=False,
        ),
    ]
